- name: "HIGH | V-1093 | AUDIT | Anonymous enumeration of shares will be restricted."
  win_command: reg query HKLM\System\CurrentControlSet\Control\Lsa /v RestrictAnonymous /t REG_DWORD /f 1
  register: anon_shares_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in anon_shares_audit.stderr and anon_shares_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-1093

- name: "HIGH | V-1093 | PATCH | Anonymous enumeration of shares will be restricted."
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Control\Lsa'
      value: RestrictAnonymous
      data: 1
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-1093

- name: "HIGH | V-1152 | AUDIT | Anonymous access to the registry must be restricted."
  win_command: reg query HKLM\SYSTEM\CurrentControlSet\Control\SecurePipeServers\Winreg
  register: anon_registry_access_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in anon_registry_access_audit.stderr and anon_registry_access_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-1152

# NOTE: V-1152 is shared between all OS's, but Backup Operators data for 2k12 is 'Read (This key only)' and for 2k8 is 'Special'.
- name: "HIGH | V-1152 | PATCH | Anonymous access to the registry must be restricted."
  win_regedit: 
      key: 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurePipeServers\Winreg'
      value: "{{ item.value }}"
      data: "{{ item.data }}"
  
  with_items: 
      - value: 'Administrators'
        data: 'Full'
      - value: 'Backup Operators'
        data: 'Read'
      - value: 'LOCAL SERVICE'
        data: 'Read' 
  tags:
      - cat1
      - high
      - patch
      - V-1152

- name: "HIGH | V-1153 | AUDIT | The LanMan authentication level must be set to send NTLMv2 response only, and to refuse LM and NTLM."
  win_command: reg query HKLM\System\CurrentControlSet\Control\Lsa /v LMCompatibilityLevel /t REG_DWORD /f 5
  register: lanMan_authentication_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in lanMan_authentication_audit.stderr and lanMan_authentication_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-1153

- name: "HIGH | V-1153 | PATCH | The LanMan authentication level must be set to send NTLMv2 response only, and to refuse LM and NTLM."
  win_regedit:
    key: 'HKLM:\System\CurrentControlSet\Control\Lsa'
    value: LMCompatibilityLevel
    data: 5
    datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-1153

- name: "HIGH | V-1159 | AUDIT | The Recovery Console option must be set to prevent automatic logon to the system."
  win_command: reg query \"HKLM\Software\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole\" /v SecurityLevel /t REG_DWORD /f 0
  register: recovery_prevent_autologin_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in recovery_prevent_autologin_audit.stderr and recovery_prevent_autologin_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-1159

- name: "HIGH | V-1159 | PATCH | The Recovery Console option must be set to prevent automatic logon to the system."
  win_regedit:
    key: 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole\'
    value: SecurityLevel
    data: 0
    datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-1159

- name: "HIGH | V-2374 | AUDIT | Autoplay must be disabled for all drives."
  win_command: reg query HKLM\Software\Microsoft\Windows\CurrentVersion\policies\Explorer\ /v NoDriveTypeAutoRun /t REG_DWORD /f 255 
  register: autoplay_disabled_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in autoplay_disabled_audit.stderr and autoplay_disabled_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-2374

- name: "HIGH | V-2374 | PATCH | Autoplay must be disabled for all drives."
  win_regedit:
      key: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\policies\Explorer\'
      value: NoDriveTypeAutoRun
      data: 255
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-2374

- name: "HIGH | V-3339 | AUDIT | Unauthorized remotely accessible registry paths must not be configured."
  win_command: reg query \"HKLM\System\CurrentControlSet\Control\SecurePipeServers\ winreg\" /v Machine /t REG_MULTI_SZ /f {{ item }}
  register: remotely_accessible_registry_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in remotely_accessible_registry_audit.stderr and remotely_accessible_registry_audit.stderr"
  with_items:
      - System\CurrentControlSet\Control\ProductOptions 
      - \"System\CurrentControlSet\Control\Server Applications\" 
      - \"Software\Microsoft\Windows NT\CurrentVersion\" 
  tags:
      - cat1
      - high
      - audit
      - V-3339

- name: "HIGH | V-3339 | PATCH | Unauthorized remotely accessible registry paths must not be configured."
  win_regedit:
    key: 'HKLM:\System\CurrentControlSet\Control\SecurePipeServers\ winreg'
    value: Machine
    data: \0System\CurrentControlSet\Control\ProductOptions\0\"System\CurrentControlSet\Control\Server Applications\"\0\"Software\Microsoft\Windows NT\CurrentVersion\"\0\0
    datatype: multistring
  changed_when: no
  tags:
      - cat1
      - high
      - patch
      - V-3339

- name: "HIGH | V-3340 | AUDIT | Network shares that can be accessed anonymously will not be allowed."
  win_command: reg query HKLM\System\CurrentControlSet\Services\LanManServer\Parameters /v NullSessionShares
  register: null_session_shares_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in null_session_shares_audit.stderr and null_session_shares_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-3340

- name: "HIGH | V-3340 | PATCH | Network shares that can be accessed anonymously will not be allowed."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters'
      value: NullSessionShares
      data: ''
      datatype: multistring
  tags:
      - cat1
      - high
      - patch
      - V-3340

- name: "HIGH | V-3343 | AUDIT | Solicited Remote Assistance must not be allowed."
  win_command: reg query \"HKLM\Software\Policies\Microsoft\Windows NT\Terminal Services\" /v fAllowToGetHelp /t REG_DWORD /f 0
  register: solicited_remote_assistance_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in solicited_remote_assistance_audit.stderr and solicited_remote_assistance_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-3343

- name: "HIGH | V-3343 | PATCH | Solicited Remote Assistance must not be allowed."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services'
      value: fAllowToGetHelp
      data: 0
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-3343

- name: "HIGH | V-3344 | AUDIT | Local accounts with blank passwords must be restricted to prevent access from the network."
  win_command: reg query HKLM\System\CurrentControlSet\Control\Lsa\ /v LimitBlankPasswordUse /t REG_DWORD /f 1
  register: blankpass_network_restriction_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in blankpass_network_restriction_audit.stderr and blankpass_network_restriction_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-3344


- name: "HIGH | V-3344 | PATCH | Local accounts with blank passwords must be restricted to prevent access from the network."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Control\Lsa\'
      value: LimitBlankPasswordUse
      data: 1
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-3344

- name: "HIGH | V-3379 | AUDIT | The system must be configured to prevent the storage of the LAN Manager hash of passwords."
  win_command: reg query HKLM\System\CurrentControlSet\Control\Lsa\ /v NoLMHash /t REG_DWORD /f 1
  register: prevent_lanman_storage_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in prevent_lanman_storage_audit.stderr and prevent_lanman_storage_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-3379

- name: "HIGH | V-3379 | PATCH | The system will be configured to prevent the storage of the LAN Manager hash of passwords."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Control\Lsa'
      value: NoLMHash
      data: 1
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-3379

- name: "HIGH | V-6834 | AUDIT | Anonymous access to Named Pipes and Shares must be restricted."
  win_command: reg query HKLM\System\CurrentControlSet\Services\LanManServer\Parameters\ /v RestrictNullSessAccess /t REG_DWORD /f 1
  register: anon_access_pipes_shares_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in anon_access_pipes_shares_audit.stderr and anon_access_pipes_shares_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-6834

- name: "HIGH | V-6834 | PATCH | Anonymous access to Named Pipes and Shares must be restricted."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters\'
      value: RestrictNullSessAccess
      data: 1
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-6834

- name: "HIGH | V-21973 | AUDIT | Autoplay must be turned off for non-volume devices."
  win_command: reg query HKLM\Software\Policies\Microsoft\Windows\Explorer\ /v NoAutoplayfornonVolume /t REG_DWORD /f 1
  register: autoplay_nonvolume_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in autoplay_nonvolume_audit.stderr and autoplay_nonvolume_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-21973

- name: "HIGH | V-21973 | PATCH | Autoplay must be turned off for non-volume devices."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\Explorer\'
      value: NoAutoplayfornonVolume
      data: 1
      datatype: dword
  tags:
      - cat1
      - high
      - patch

- name: "HIGH | V-22692 | AUDIT | The default Autorun behavior must be configured to prevent Autorun commands."
  win_command: reg query HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\ /v NoAutorun /t REG_DWORD /f 1
  register: autorun_prevent_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in autorun_prevent_audit.stderr and autorun_prevent_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-22692

- name: "HIGH | V-22692 | PATCH | The default Autorun behavior must be configured to prevent Autorun commands."
  action: win_ping
  tags:
      - cat1
      - high
      - patch
      - V-22692

- name: "HIGH | V-26283 | AUDIT | Anonymous enumeration of SAM accounts must not be allowed."
  win_command: reg query HKLM\System\CurrentControlSet\Control\Lsa\ /v RestrictAnonymousSAM /t REG_DWORD /f 1
  register: anonymous_enum_sam_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in anonymous_enum_sam_audit.stderr and anonymous_enum_sam_audit.stderr"
  tags:
      - cat1
      - high
      - audit
      - V-26283

- name: "HIGH | V-26283 | PATCH | Anonymous enumeration of SAM accounts must not be allowed."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Control\Lsa\'
      value: RestrictAnonymousSAM
      data: 1
      datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-26283
