- name: "MEDIUM | V-1097 | AUDIT | The system must lockout accounts after 3 invalid logon attempts within a specified time period."
  win_shell: net accounts | select-string -Pattern "threshold"
  register: lockout_threshold_audit
  check_mode: no
  changed_when: no
  tags:
      - cat2
      - medium
      - audit
      - V-1097

- name: "MEDIUM | V-1097 | PATCH | The system must lockout accounts after 3 invalid logon attempts within a specified time period."
  win_shell: net accounts /lockoutthreshold:5
  when: "'5' not in lockout_threshold_audit.stdout"
  tags:
      - cat2
      - medium
      - patch
      - V-1097

- name: "MEDIUM | V-1099 | AUDIT | The account lockout duration must be configured to require an administrator to unlock an account."
  debug: var=secedit_rules.System_Access.LockoutDuration
  check_mode: no
  changed_when: no
  tags:
      - cat2
      - medium
      - audit
      - V-1099

- name: "MEDIUM | V-1099 | PATCH | The account lockout duration must be configured to require an administrator to unlock an account."
  win_secedit: 
      category: 'System Access'
      key: LockoutDuration
      value: -1
  register: secedit
  failed_when: "secedit.failed is defined and 'This host is joined to a Domain Controller' not in secedit.msg"
  tags:
      - cat2
      - medium
      - patch
      - V-1099

- name: "MEDIUM | V-1104 | AUDIT | The maximum password age must be configured to 60 days or less."
  win_shell: net accounts | Select-String -Pattern "Max"
  register: max_password_age_audit
  check_mode: no
  changed_when: no
  tags:
      - cat2
      - medium
      - audit
      - V-1104

- name: "MEDIUM | V-1104 | PATCH | The maximum password age must be configured to 60 days or less."
  win_command: net accounts /maxpwage:60
  when: "'60' not in max_password_age_audit.stdout"
  tags:
      - cat2
      - medium
      - patch
      - V-1104

- name: "MEDIUM | V-1105 | AUDIT | The minimum password age must be configured to at least 1 day."
  debug: var=secedit_rules.System_Access.MinimumPasswordAge
  check_mode: no
  changed_when: no
  tags:
      - cat2
      - medium
      - audit
      - V-1105

- name: "MEDIUM | V-1105 | PATCH | The minimum password age must be configured to at least 1 day."
  win_command: net accounts /minpwage:0
  when: secedit_rules.System_Access.MinimumPasswordAge != "0"
  tags:
      - cat2
      - medium
      - patch
      - V-1105


- name: "MEDIUM | V-1107 | AUDIT | The password history must be configured to 24 passwords remembered."
  debug: var=secedit_rules.System_Access.PasswordHistorySize
  check_mode: no
  changed_when: no
  tags:
      - cat2
      - medium
      - audit
      - V-1107

- name: "MEDIUM | V-1107 | PATCH | The password history must be configured to 24 passwords remembered."
  win_secedit:
      category: 'System Access'
      key: PasswordHistorySize
      value: '12'
  register: secedit
  failed_when: "secedit.failed is defined and 'This host is joined to a Domain Controller' not in secedit.msg"
  tags:
      - cat2
      - medium
      - patch
      - V-1107

- name: "MEDIUM | V-1113 | AUDIT | The built-in guest account must be disabled."
  debug: var=secedit_rules.System_Access.EnableGuestAccount
  check_mode: no
  changed_when: no
  tags:
      - cat2
      - medium
      - audit
      - V-1113

- name: "MEDIUM | V-1113 | PATCH | The built-in guest account must be disabled."
  win_secedit:
      category: 'System Access'
      key: EnableGuestAccount
      value: '0'
  register: secedit
  failed_when: "secedit.failed is defined and 'This host is joined to a Domain Controller' not in secedit.msg"
  tags:
      - cat2
      - medium
      - patch
      - V-1113

- name: "MEDIUM | V-1119 | AUDIT | Booting into alternate non STIG compliant operating systems will not be permitted."
  win_command: bcdedit
  register: OS_list_audit
  check_mode: no
  changed_when: no
  tags:
      - cat2
      - medium
      - audit
      - V-1119

- name: "MEDIUM | V-1141 | AUDIT | Unencrypted passwords must not be sent to third-party SMB Servers."
  win_command: reg query HKLM\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters /v EnablePlainTextPassword
  register: plain_text_password_audit
  check_mode: no
  changed_when: no
  failed_when: "reg_not_found not in plain_text_password_audit.stderr and plain_text_password_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-1141

- name: "MEDIUM | V-1141 | PATCH | Unencrypted passwords must not be sent to third-party SMB Servers."
  win_regedit:
      key: 'HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters'
      value: EnablePlainTextPassword
      data: 0
      datatype: dword
  tags:
      - cat2
      - medium
      - patch
      - V-1141

- name: "MEDIUM | V-1145 | AUDIT | Automatic logons must be disabled."
  win_command: reg query \"HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\" /v AutoAdminLogon
  register: disable_automatic_logons_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  failed_when: "reg_not_found not in disable_automatic_logons_audit.stderr and disable_automatic_logons_audit.stderr"
  tags:
      - cat2
      - medium
      - audit
      - V-1145

- name: "MEDIUM | V-1145 | PATCH | Automatic logons must be disabled."
  win_regedit:
    key: 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon'
    value: AutoAdminLogon
    data: 0
  tags:
      - cat2
      - medium
      - patch
      - V-1145

- name: "MEDIUM | V-1150 | AUDIT | The built-in Windows password complexity policy must be enabled."
  debug: var=secedit_rules.System_Access.PasswordComplexity
  check_mode: no
  changed_when: no
  tags:
      - cat2
      - medium
      - audit
      - V-1150

- name: "MEDIUM | V-1150 | PATCH | The built-in Windows password complexity policy must be enabled."
  win_secedit:
      category: 'System Access'
      key: PasswordComplexity
      value: '1'
  register: secedit
  failed_when: "secedit.failed is defined and 'This host is joined to a Domain Controller' not in secedit.msg"
  tags:
      - cat2
      - medium
      - patch
      - V-1150
