- name: "MEDIUM | V-1097 | AUDIT | The system must lockout accounts after 3 invalid logon attempts within a specified time period."
  win_shell: net accounts | select-string -Pattern "threshold"
  register: lockout_threshold_audit
  check_mode: no
  changed_when: no
  tags:
      - cat2
      - medium
      - audit
      - V-1097

- name: "MEDIUM | V-1097 | PATCH | The system must lockout accounts after 3 invalid logon attempts within a specified time period."
  win_shell: net accounts /lockoutthreshold:5
  when: "'5' not in lockout_threshold_audit.stdout"
  tags:
      - cat2
      - medium
      - patch
      - V-1097

- name: "MEDIUM | V-1099 | AUDIT | The account lockout duration must be configured to require an administrator to unlock an account."
  debug: var=secedit_rules.System_Access.LockoutDuration
  check_mode: no
  changed_when: no
  tags:
      - cat2
      - medium
      - audit
      - V-1099

- name: "MEDIUM | V-1099 | PATCH | The account lockout duration must be configured to require an administrator to unlock an account."
  win_secedit: 
      category: 'System Access'
      key: LockoutDuration
      value: -1
  register: secedit
  failed_when: "secedit.failed is defined and 'This host is joined to a Domain Controller' not in secedit.msg"
  tags:
      - cat2
      - medium
      - patch
      - V-1099

- name: "MEDIUM | V-1104 | AUDIT | The maximum password age must be configured to 60 days or less."
  win_shell: net accounts | Select-String -Pattern "Max"
  register: max_password_age_audit
  check_mode: no
  changed_when: no
  tags:
      - cat2
      - medium
      - audit
      - V-1104

- name: "MEDIUM | V-1104 | PATCH | The maximum password age must be configured to 60 days or less."
  win_command: net accounts /maxpwage:60
  when: "'60' not in max_password_age_audit.stdout"
  tags:
      - cat2
      - medium
      - patch
      - V-1104

- name: "MEDIUM | V-1105 | AUDIT | The minimum password age must be configured to at least 1 day."
  debug: var=secedit_rules.System_Access.MinimumPasswordAge
  check_mode: no
  changed_when: no
  tags:
      - cat2
      - medium
      - audit
      - V-1105

- name: "MEDIUM | V-1105 | PATCH | The minimum password age must be configured to at least 1 day."
  win_command: net accounts /minpwage:0
  when: secedit_rules.System_Access.MinimumPasswordAge != "0"
  tags:
      - cat2
      - medium
      - patch
      - V-1105
